### ISSUE TITLE
[Feature Request] Allow setting a minimum bid to accept a block from a relay

### ISSUE THREAD

**Issue by ThomasDalla** [attestantio/vouch#102]
##  Summary
 
Add a `minimum bid` parameter to the MEV strategy to allow setting a minimum bid to accept a block from a relay.\
Ideally a top-level minimum bid as well as overrides per relay.

 ## Motivation and Context
 
https://github.com/flashbots/mev-boost/issues/273

Implemented in https://github.com/flashbots/mev-boost/pull/274

**Comment by mcdee** [comment]
This feature should now be available in the https://github.com/attestantio/vouch/tree/execution-config-v2 branch.  If possible, please compile this branch and run it in your test environment to confirm that it meets your requirement.  If not, please read https://github.com/attestantio/vouch/blob/execution-config-v2/docs/executionconfig.md for the same.

**Comment by mcdee** [comment]
Please try `attestant/vouch:execution-config-v2`

**Comment by mcdee** [comment]
Any feedback on this PR?  I'm looking to merge it in the coming week so any information you may have on it would be appreciated.

**Comment by mcdee** [comment]
Thanks for the feedback.

**Comment by mcdee** [comment]
Thank you for reporting this.  It is a bug in the selection mechanism for bids, with a fix in #121 that will be included in release 1.7.0.
