### ISSUE TITLE
How could I exit a validator if I use vouch to  manage serval validators?

### ISSUE THREAD

**Issue by pursonchen** [attestantio/vouch#132]
How could I exit a validator if I use vouch to manage serval validators?

**Comment by mcdee** [comment]
You can create and broadcast an exit transaction using `ethdo`, try `ethdo validator exit --help` for details.

**Comment by pursonchen** [comment]
Thanks.

**Comment by pursonchen** [comment]
> You can create and broadcast an exit transaction using `ethdo`, try `ethdo validator exit --help` for details.

Could you give me an example of generating and broadcasting the exit message on threshold 2/3  architecture built on vouch & dirk?

**Comment by mcdee** [comment]
You need to ensure that you are allowed to create exits, which is controlled by the 'server.name.admin-ips' list.  In your `.dirk.yml` files you need:

```
server:
  rules:
    admin-ips: ['1.2.3.4']
```

Replacing the IP address with the server from which you wish to generate exits.

**Comment by pursonchen** [comment]
> You need to ensure that you are allowed to create exits, which is controlled by the 'server.rules.admin-ips' list. In your `.dirk.yml` files you need:
> 
> ```
> server:
>   rules:
>     admin-ips: ['1.2.3.4']
> ```
> 
> Replacing the IP address with the server from which you wish to generate exits.

Works well! Thank you!
