### ISSUE TITLE
Advanced Scheduler Issue - Vouch Ceased To Work

### ISSUE THREAD

**Issue by SimonKraus** [attestantio/vouch#249]
Today we had an incident in one of our clusters. 
Due to our setup (running vouch in a screen, `log-level: debug` and `log-file: /custom/path` in the `.vouch.yml`) we were not able to capture all the output of the vouch process and were limited by the screen-buffer.

The captured messages can be found here => https://gist.github.com/SimonKraus/b70bbf8e49d689252496c76ed89dda09

Vouch is running on version 1.8.0 and we have never encountered a similar issue in the past.

The vouch in this setup is paired with one dirk instance and 6 beacon-nodes in the following client configurations:

- Pry-Geth
- LHS-Geth
- Nim-Geth
- Tek-Geth
- Tek-Nethr
- Nim-Nethr

If there's any other useful information we could provide please just let us know

**Comment by mcdee** [comment]
Unfortunately this is not the whole log, so the cause of the crash is not available.  However, there was a fix in 1.8.1 for a concurrent read/write to a map that would cause this sort of output, so it is possible that upgrading to 1.8.1 will address it.

**Comment by SimonKraus** [comment]
Thank you very much. 
We'll update the vouch clients and make sure to persist the crashlogs in case this happens again. 

Really appreciate the fast reaction on this.
