### ISSUE TITLE
[feature request] Support accounts in the Blockrelay config section

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [attestantio/vouch#89]
Rewriting proposer_config in the `blockrelay` section based on `accounts` from the `accountmanager` section, not based on a single validator.
In my case, I have different `accounts` with multi keys(about 200 for each). 
For each `account` I need to specify a different `fee_ recipient`. 
And current config is a bit messy now with a lot of copypaste.

**Comment by mcdee** [comment]
This feature should now be available in the https://github.com/attestantio/vouch/tree/execution-config-v2 branch.  If possible, please compile this branch and run it in your test environment to confirm that it meets your requirement.  If not, please read https://github.com/attestantio/vouch/blob/execution-config-v2/docs/executionconfig.md for the same.

**Comment by SpontaneousOverthrow** [comment]
ty, gonna test next week or so

**Comment by mcdee** [comment]
Any feedback on this PR?  I'm looking to merge it in the coming week so any information you may have on it would be appreciated.
