### ISSUE TITLE
[Feature Request] Support web3signer as an account manager

### ISSUE THREAD

**Issue by ThomasDalla** [attestantio/vouch#97]
In a world where most of the existing validators have been created with hd wallets, this is currently impossible to migrate them to Vouch _with_ slashing protection.
We can migrate them to local wallet accounts in Vouch, and under normal operations Vouch does not produce slashing events, but having a robust slashing protection would be better (especially if we benefit from it with the current validator client we are running and want to migrate to Vouch).

Supporting web3signer as an account manager would make it possible to migrate existing non-ditributed validators to Vouch while retaining slashing protection.
It would help increase Vouch's adoption.

**Comment by mcdee** [comment]
If you have an HD seed you can create an HD wallet with the relevant accounts using `ethdo` and serve it using `dirk` to provide slashing protection.  Does this address the issue?

**Comment by mcdee** [comment]
I spent some time looking at the web3signer, and think that rather than supporting it a better way to go will be to provide the ability to shard an existing private key.  This would leverage Dirk's slashing protection and not require shared infrastructure.

**Comment by ybstaked** [comment]
Great discussion, very interested in this feature being available!
